#############################################################
# Terraform Apply/Destroy
# 
# This pipeline will allow a Terraform template to be
# applied and destroyed.
#############################################################
name: 'Terraform CI'

trigger: 'none'
# trigger:
#   batch: true
#   branches:
#     include:
#     - master
#   paths:
#     include:
#     - 'path/to/terraform/root'

variables:
- group: 'shared-terraform'
## Contains:
## * agentPool
## * terraformAzureSubscription
## * terraformStorageAccount
## * terraformWorkingDirectoryBase
## Set these variables on pipeline creation or uncomment and update in here if it will be static
# - name: 'templateName'
#   value: 'REPLACE_ME'
# - name: 'terraformApply'
#   value: false
# - name: 'terraformDestroy'
#   value: false

pool:
  name: '$(agentPool)'

stages:
# Template stage used to do a Terraform run.
# This cannot be reused due to jobs requiring unique names.
- template: '/.devops/pipelines/templates/terraformRun.tpl.stage.yml'
  parameters:
    terraformWorkingDirectory: '$(terraformWorkingDirectoryBase)/$(templateName)'
    azureSubscription: '$(terraformAzureSubscription)'
    terraformStorageAccount: '$(terraformStorageAccount)'
    terraformWorkspace: ''
    terraformApply: '$(terraformApply)'
    terraformDestroy: '$(terraformDestroy)'
    terraformInputVariables: {}
